function [eps] = defineEpochs_regression(nantype)


names={'OGbase','TM slow','TM base','Adaptation','Post1_{Early}','Post1_{Late}','Post2_{Early}','Post2_{Late}','Post1-Adapt_{SS}','PosShort_{early}-TMbase'};

eps=defineEpochs(names,...
                {'OG base','TM slow','TM base','Adaptation','Washout','Washout','OG washout','OG washout','Washout','Short Pos'},...
                [-40 -40 -40 -40 5 -40 5 -40 5 10],...
                [0,0,0,0,1,0,1,0,1,1],...
                [5,5,5,5,0,5,0,5,0,1],...
                nantype);