function [eps] = defineRegressors_StrokeC3(nantype)


names={'TM fast','TM base','Adaptation','Adaptation_{early}',...
    'Post1_{Early}','Post1_{Late}','Post2_{Early}','Post2_{Late}',...
      'PosShort_{early}','PosShort_{late}', 'NegShort_{early}','NegShort_{late}',...
      'TiedPostPos','TMmid2','OG2','TMbase_{early}',...
      'Tied post Neg','OG base'};


eps=defineEpochs(names,...
                {'TM fast','TM base','Adaptation','Adaptation'...
                'Post 1','Post 1','Post 2','Post 2',...
                 'Short Pos','Short Pos','Short Neg', 'Short Neg',...
                 'Tied post Pos','TM mid 2','OG 2','TM base',...
                 'Tied post Neg','OG base'},...
                [-40 -35 -40 5,...
                5 -40 5 -40,...
                10 -10 10 -10,...
                30 30 30 10,...
                10 -40],...
                [0,0,0,1,...
                1,0,1,0,...
                1 0 1 0,...
                1 1 1 1,...
                1 0],...
                [5, 5,5,0,...
                0,5,0,5,...
                0 5 0 5,...
                0 0 0 0,...
                0 5],...
                nantype);