function [eps] = defineEpochs_regression_running(nantype,strides)


names={'OG base','TM slow','TR base','Adaptation',...
    'Post1_{Early}','Post1_{Late}','Post2_{Early}',...
    'Post2_{Late}','Post1-Adapt_{SS}','PosShort_{early}-TMbase',...
    'Pos Short','Neg Short'};

eps=defineEpochs(names,...
                {'OG base','TM slow','TR base','Adaptation',...
                'Post 1','Post 1','Post 2',...
                'Post 2','Post 1','Short Pos',...
                'Pos Short','Neg Short'},...
                [1 -40 1 1,...
                1 -40 1,...
                -40 5 10,...
                1 1],...
                [strides,0,strides,strides,...
                strides,0,strides,...
                0,0,1,...
                strides,strides],...
                [1,1,1,1,...
                1,1,1,...
                1,1,1,...
                1,1],...
                nantype);